---
# tasks file for nginxinst
- name: Nginx installation
  block:

  - name: Add Nginx repository on CentOS/RHEL
    become: yes
    yum_repository:
      name: nginx
      description: Official Nginx repository
      baseurl: http://nginx.org/packages/centos/$releasever/$basearch/
      gpgcheck: true
      gpgkey: https://nginx.org/keys/nginx_signing.key
      enabled: true
  - name: Install Nginx on CentOS/RHEL latest version
    become: yes
    yum:
      name: nginx
      state: latest
      update_cache: true
  - name: Install Nginx on CentOS/RHEL specific version 
    become: yes
    yum:
      name: nginx
      state: present
      allow_downgrade: true # если мы захотим переустановить пакет меньшей версии
      update_cache: true
  - name: Start Nginx service
    become: yes
    service:
      name: nginx
      state: started    # переводим в состояние «запущено»
      enabled: yes      # добавляем в автозагрузку
  - name: Install python3-passlib
    become: yes
    yum:
      name: python3-passlib
      state: latest
      update_cache: true
