---
# defaults file for nginxinst
company: Welcome to the secret page
passwd: '    location / {
        auth_basic "Restricted Access";
        auth_basic_user_file /etc/nginx/.htpasswd;
        
        root /var/www/html;
        index index.html index.htm; } '
